language: go
go:
- 1.3
- 1.4
sudo: false
services:
- memcache
- redis-server
- postgresql
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database ladybug;' -U postgres
install:
- export PATH=$PATH:$HOME/gopath/bin
- go get -v github.com/revel/revel/...
- go get -v github.com/agtorre/gocolorize
- go get -v github.com/robfig/config
- go get -v github.com/robfig/pathtree
- go get -v github.com/revel/cmd/revel
- go get -v github.com/revel/revel/cache
- go get -v gopkg.in/fsnotify.v1
- go get -v github.com/lib/pq
- go get -v github.com/jinzhu/gorm
- go get -v github.com/robfig/cron
- go get -v golang.org/x/crypto/bcrypt
script:
- revel test github.com/wisedog/ladybug
notifications:
  slack: jonghakim:3MifSQNabecHhOm0h65QRHLj
deploy:
  provider: openshift
  user: kim.jongha@gmail.com
  password:
    secure: lY4rKy/x7HYj9td6cKvi93Anmjszl70Rk1pJfK7K/zcNkOF5diwfTZ8LrGc+XvaE/QsgkCVSCvfgdIRDltxpQKBfZnQ6SJhK87OZk9ofIAiC8xl36JbJN/w0R81sFEkIMSRnGN9CW7KZe598QgNits2GBUF04qx4McfOcm4RwAIjUmgWlFGT3KUTUjIefzCP0QOpa2VwtpB34xksEYNE8aJfa153hYexpKjTCPKeZlcy87jsQQHActsLhuYLEnNOjx5uk0Aee2yi2tKzrsle312RVGKBiN92BLgTsBm/Cg8EenLR6c5tLZSi1/B4DcsY5BY6r2qu+/q8MfOL19zoMBGPndp68Cb0opYe3RlHP3Atv0EaOrH2/o/CT+hVk+pQDSnNoArkbdwspjtfwjOmKG/VOFbICzLHiT4BDeizeyF9THDGJgKMbKILZGruc99L01hl4lSKX7tdtyUuVXa74RSu8SOlJqU1iZoVuWXstKzkB8B2ilBke+cyetsS3s25TEbIWP3xyhzXVvEOfPIgPaSvxanq+o6bmvgGSgyD3am6MAOFBjM0k9cYlszAXTQ3LiAJ/U9I1F6/BrxrYYBZJZSCyJAMpypra45sEc1WX8DBTNeF1IdWIGjflb8mFnZ0mKSTU585hiMxapC4okhrAAfXpQ54z7mcEMVYUNLKp9k=
  app: ladybug
  domain: wisedog-ladybugdev.rhcloud.com
  on:
    repo: wisedog/ladybug
    branch: openshift-deploy
